server:
  port: 8989

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    #公司虚拟机
    url: jdbc:mysql://mysql:3306/aspn?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
    password: aspn2021
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
  mail:
    host: mail.aspnc.com
    port: 25
    username: aspn300@aspnc.com
    password: Aspn20200612!@#
    properties.mail.smtp:
      #      socketFactoryCalss: javax.net.ssl.SSLSocketFactory
      timeout: 5000
      connectiontimeout: 5000
      writetimeout: 5000
    default-encoding: UTF-8


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_null


#logging:
#  config: classpath:logback.xml
#  level.org.springframework.boot.autoconfigure: info #spring的自动装配日志只打error，否则debug输出的会打印很多自动装配的log信息到控制台

ftp:
  hostName: 192.168.0.116
  port: 21
  userName: wikiprd
  passWord: wiki1357
  baseFile: /
  localFile: /aspn/backup/
  mysqlBackup: mysqlBackup_
  minIoBackup: minIoBackup_

